### ISSUE TITLE
Porting to ESPHOME

### ISSUE THREAD

**Issue by xekil** [neutrinus/everblu-meters#2]
Hello,

Thank you very much for this project, would it be possible to adapt it to ESPHOME?

Thanks

**Comment by neutrinus** [comment]
I would love  to see it working on esphome!

As everblu meter needs long signal to "wake it up", I'm not sure if it's possible with esphome. 

As you can read on https://esphome.io/guides/contributing.html

` One thing to note in these methods is that anything in loop() or setup() should not block. Specifically methods like delay(10) should be avoided and delays above ~10ms are not permitted. The reason for this is that ESPHome uses a central single-threaded loop for all components - if your component blocks the whole loop will be slowed down.`

Current code is blocking, so that would have to be rewritten.

**Comment by xekil** [comment]
Thanks for the reply, I'll forget that idea then :(
I'm waiting to receive the cc1101 module to get started :)
